const char* const arbitration_abi = R"=====(
{
  "____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-05-29T19:49:46",
  "version": "",
  "types": [{
      "new_type_name": "account_name",
      "type": "name"
    },{
      "new_type_name": "time",
      "type": "uint32"
    }
  ],
  "structs": [{
      "name": "document",
      "base": "",
      "fields": [{
          "name": "description",
          "type": "string"
        },{
          "name": "link",
          "type": "string"
        },{
          "name": "hash_of_contents",
          "type": "checksum256"
        }
      ]
    },{
      "name": "sbmttdflng",
      "base": "",
      "fields": [{
          "name": "id",
          "type": "uint64"
        },{
          "name": "for_case",
          "type": "uint64"
        },{
          "name": "belongs_to",
          "type": "account_name"
        },{
          "name": "documents",
          "type": "document[]"
        },{
          "name": "tx_ids",
          "type": "string[]"
        },{
          "name": "can_delete",
          "type": "bool"
        }
      ]
    },{
      "name": "claim",
      "base": "",
      "fields": [{
          "name": "id",
          "type": "uint64"
        },{
          "name": "claimant",
          "type": "account_name"
        },{
          "name": "respondents",
          "type": "account_name[]"
        },{
          "name": "tx_ids",
          "type": "string[]"
        },{
          "name": "documents",
          "type": "document[]"
        },{
          "name": "claim_dropped",
          "type": "bool"
        },{
          "name": "can_delete",
          "type": "bool"
        },{
          "name": "is_rejected",
          "type": "bool"
        },{
          "name": "rejection_reason",
          "type": "document"
        },{
          "name": "fee",
          "type": "asset"
        },{
          "name": "fee_paid",
          "type": "bool"
        },{
          "name": "bond",
          "type": "asset"
        },{
          "name": "bond_fronted",
          "type": "bool"
        }
      ]
    },{
      "name": "filing",
      "base": "",
      "fields": [{
          "name": "belongs_to",
          "type": "account_name"
        },{
          "name": "documents",
          "type": "document[]"
        },{
          "name": "tx_ids",
          "type": "string[]"
        }
      ]
    },{
      "name": "arbcase",
      "base": "",
      "fields": [{
          "name": "id",
          "type": "uint64"
        },{
          "name": "claimants",
          "type": "account_name[]"
        },{
          "name": "respondents",
          "type": "account_name[]"
        },{
          "name": "arbitrators",
          "type": "account_name[]"
        },{
          "name": "filings",
          "type": "filing[]"
        },{
          "name": "time_opened",
          "type": "time"
        },{
          "name": "case_dropped",
          "type": "bool"
        },{
          "name": "can_delete",
          "type": "bool"
        },{
          "name": "is_resolved",
          "type": "bool"
        },{
          "name": "time_closed",
          "type": "time"
        },{
          "name": "fee",
          "type": "asset"
        },{
          "name": "fee_paid",
          "type": "bool"
        },{
          "name": "bond",
          "type": "asset"
        },{
          "name": "bond_fronted",
          "type": "bool"
        },{
          "name": "bond_dispersed",
          "type": "bool"
        },{
          "name": "ruling",
          "type": "document"
        },{
          "name": "remedy",
          "type": "document"
        },{
          "name": "requested_remedy",
          "type": "bool"
        },{
          "name": "remedy_fulfilled",
          "type": "bool"
        }
      ]
    },{
      "name": "crlog",
      "base": "",
      "fields": [{
          "name": "id",
          "type": "account_name"
        },{
          "name": "claimant_on_case_id",
          "type": "uint64[]"
        },{
          "name": "respondent_on_case_id",
          "type": "uint64[]"
        }
      ]
    },{
      "name": "arbfee",
      "base": "",
      "fields": [{
          "name": "fee",
          "type": "asset"
        }
      ]
    },{
      "name": "submitclaim",
      "base": "",
      "fields": [{
          "name": "claimant",
          "type": "account_name"
        },{
          "name": "respondents",
          "type": "account_name[]"
        },{
          "name": "tx_ids",
          "type": "string[]"
        },{
          "name": "documents",
          "type": "document[]"
        },{
          "name": "fee",
          "type": "asset"
        }
      ]
    },{
      "name": "submitfiling",
      "base": "",
      "fields": [{
          "name": "party",
          "type": "account_name"
        },{
          "name": "case_id",
          "type": "uint64"
        },{
          "name": "tx_ids",
          "type": "string[]"
        },{
          "name": "documents",
          "type": "document[]"
        }
      ]
    },{
      "name": "deletefiling",
      "base": "",
      "fields": [{
          "name": "sf_id",
          "type": "uint64"
        },{
          "name": "party",
          "type": "account_name"
        }
      ]
    },{
      "name": "addfiling",
      "base": "",
      "fields": [{
          "name": "sf_id",
          "type": "uint64"
        },{
          "name": "case_id",
          "type": "uint64"
        },{
          "name": "arbitrator",
          "type": "account_name"
        }
      ]
    },{
      "name": "dropclaim",
      "base": "",
      "fields": [{
          "name": "claim_id",
          "type": "uint64"
        },{
          "name": "claimant",
          "type": "account_name"
        }
      ]
    },{
      "name": "deleteclaim",
      "base": "",
      "fields": [{
          "name": "claim_id",
          "type": "uint64"
        },{
          "name": "claimant",
          "type": "account_name"
        }
      ]
    },{
      "name": "deletecase",
      "base": "",
      "fields": [{
          "name": "case_id",
          "type": "uint64"
        },{
          "name": "arbitrator",
          "type": "account_name"
        }
      ]
    },{
      "name": "candltcase",
      "base": "",
      "fields": [{
          "name": "case_id",
          "type": "uint64"
        },{
          "name": "arbitrator",
          "type": "account_name"
        }
      ]
    },{
      "name": "rejectclaim",
      "base": "",
      "fields": [{
          "name": "claim_id",
          "type": "uint64"
        },{
          "name": "rr",
          "type": "document"
        }
      ]
    },{
      "name": "submitruling",
      "base": "",
      "fields": [{
          "name": "case_id",
          "type": "uint64"
        },{
          "name": "ruling",
          "type": "document"
        },{
          "name": "arbitrator",
          "type": "account_name"
        }
      ]
    },{
      "name": "closecase",
      "base": "",
      "fields": [{
          "name": "case_id",
          "type": "uint64"
        },{
          "name": "arbitrator",
          "type": "account_name"
        }
      ]
    },{
      "name": "assignarb",
      "base": "",
      "fields": [{
          "name": "arbcase_id",
          "type": "uint64"
        },{
          "name": "arbitrator",
          "type": "account_name"
        }
      ]
    },{
      "name": "removearb",
      "base": "",
      "fields": [{
          "name": "arbcase_id",
          "type": "uint64"
        },{
          "name": "arbitrator",
          "type": "account_name"
        }
      ]
    },{
      "name": "opencase",
      "base": "",
      "fields": [{
          "name": "claim_id",
          "type": "uint64"
        }
      ]
    },{
      "name": "remedyr",
      "base": "",
      "fields": [{
          "name": "case_id",
          "type": "uint64"
        },{
          "name": "arbitrator",
          "type": "account_name"
        },{
          "name": "remedy",
          "type": "document"
        }
      ]
    },{
      "name": "remedyf",
      "base": "",
      "fields": [{
          "name": "id",
          "type": "uint64"
        },{
          "name": "arbitrator",
          "type": "account_name"
        }
      ]
    },{
      "name": "setbond",
      "base": "",
      "fields": [{
          "name": "claim_id",
          "type": "uint64"
        },{
          "name": "bond",
          "type": "asset"
        }
      ]
    },{
      "name": "frontbond",
      "base": "",
      "fields": [{
          "name": "claim_id",
          "type": "uint64"
        },{
          "name": "claimant",
          "type": "account_name"
        },{
          "name": "bond",
          "type": "asset"
        }
      ]
    },{
      "name": "setarbfee",
      "base": "",
      "fields": [{
          "name": "fee",
          "type": "asset"
        }
      ]
    }
  ],
  "actions": [{
      "name": "submitclaim",
      "type": "submitclaim",
      "ricardian_contract": ""
    },{
      "name": "submitfiling",
      "type": "submitfiling",
      "ricardian_contract": ""
    },{
      "name": "deletefiling",
      "type": "deletefiling",
      "ricardian_contract": ""
    },{
      "name": "addfiling",
      "type": "addfiling",
      "ricardian_contract": ""
    },{
      "name": "dropclaim",
      "type": "dropclaim",
      "ricardian_contract": ""
    },{
      "name": "deleteclaim",
      "type": "deleteclaim",
      "ricardian_contract": ""
    },{
      "name": "deletecase",
      "type": "deletecase",
      "ricardian_contract": ""
    },{
      "name": "candltcase",
      "type": "candltcase",
      "ricardian_contract": ""
    },{
      "name": "rejectclaim",
      "type": "rejectclaim",
      "ricardian_contract": ""
    },{
      "name": "submitruling",
      "type": "submitruling",
      "ricardian_contract": ""
    },{
      "name": "closecase",
      "type": "closecase",
      "ricardian_contract": ""
    },{
      "name": "assignarb",
      "type": "assignarb",
      "ricardian_contract": ""
    },{
      "name": "removearb",
      "type": "removearb",
      "ricardian_contract": ""
    },{
      "name": "opencase",
      "type": "opencase",
      "ricardian_contract": ""
    },{
      "name": "remedyr",
      "type": "remedyr",
      "ricardian_contract": ""
    },{
      "name": "remedyf",
      "type": "remedyf",
      "ricardian_contract": ""
    },{
      "name": "setbond",
      "type": "setbond",
      "ricardian_contract": ""
    },{
      "name": "frontbond",
      "type": "frontbond",
      "ricardian_contract": ""
    },{
      "name": "setarbfee",
      "type": "setarbfee",
      "ricardian_contract": ""
    }
  ],
  "tables": [{
      "name": "sbmttdflng",
      "index_type": "i64",
      "key_names": [
        "id"
      ],
      "key_types": [
        "uint64"
      ],
      "type": "sbmttdflng"
    },{
      "name": "claim",
      "index_type": "i64",
      "key_names": [
        "id"
      ],
      "key_types": [
        "uint64"
      ],
      "type": "claim"
    },{
      "name": "arbcase",
      "index_type": "i64",
      "key_names": [
        "id"
      ],
      "key_types": [
        "uint64"
      ],
      "type": "arbcase"
    },{
      "name": "crlog",
      "index_type": "i64",
      "key_names": [
        "id"
      ],
      "key_types": [
        "account_name"
      ],
      "type": "crlog"
    },{
      "name": "arbfee",
      "index_type": "i64",
      "key_names": [
        "fee"
      ],
      "key_types": [
        "asset"
      ],
      "type": "arbfee"
    }
  ],
  "ricardian_clauses": [],
  "error_messages": [],
  "abi_extensions": []
}
)=====";